version: "3.3"

services:
  api:
    image: go-learn
    container_name: go-learn-api
    build:
      context: .
      args:
        ENV: local
        http_proxy: "${HTTP_PREFIX}${HTTP_PROXY}"
        https_proxy: "${HTTP_PREFIX}${HTTPS_PROXY}"
        GIT_USERNAME: "${GIT_USERNAME}"
    expose:
      - "80"
    ports:
      - "80:80"
    environment:
      - "http_proxy=${HTTP_PREFIX}${HTTP_PROXY}"
      - "https_proxy=${HTTP_PREFIX}${HTTPS_PROXY}"
      - "no_proxy=${NO_PROXY}"
